name 'workstations'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures workstations'
long_description 'Installs/Configures workstations'
version '0.1.0'

depends 'sudo'
depends 'chef-ingredient'
